version: '3.8'

services:
  myapp:
    build: ./app
    #image: myapp:0.1
    ports:
      - 8000:8000
    depends_on:
      - database
    #restart: always

  database:
    image: mysql
    volumes:
      - myapp_db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    #restart: always
    environment:
      MYSQL_DATABASE: myapp_db
      MYSQL_ROOT_PASSWORD: example
    #ports:
    #  - "3306:3306"

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - database

volumes:
  myapp_db:
    driver: local
